# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56c7d2ead10daadc479462d8f2a77fb30a0ef94b27580b78bf1d95a995315138d10ec94e2b929629bef436f85523f1a13bdfdb5a8d8799d8a7e0f0e0e45fbd0b

test:
  secret_key_base: 2e6df79cd88a3e010a7a3ed2b5c8815d0afe8e298427534eef58f4ff86c14bc80ad2e554f71603fa1c7cfb809711309a12dabc5ec380ba65073dce507861a452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
